### ISSUE TITLE
Interested in getting this working on Pantheon

### ISSUE THREAD

**Issue by herbdool** [ChrisChinchilla/com.schwartzmedia.rediscache#1]
Is this related to this CiviCRM issue? https://issues.civicrm.org/jira/plugins/servlet/mobile#issue/CRM-14457

In that issue it seems that core needed to be patched. And that work still needed to be done to get it working on Pantheon. I'm interested in knowing your progress and also helping in some way. We've got a client who we've just moved to Pantheon and I think getting Redis working on CiviCRM would be a big help. Thanks!

**Comment by ChrisChinchilla** [comment]
Go for it, I wont have any time right now, please fork away and get things working. My main issue was testing this on Patheon setups. From what I remember it worked fine and should be pretty easy to get going again.

**Comment by herbdool** [comment]
Ok, so CiviCRM core doesn't need to be patched? So just got to get it working on Pantheon.

**Comment by herbdool** [comment]
From this [issue](https://issues.civicrm.org/jira/browse/CRM-14457) Lobo mentioned that the core Cache.php file needed to be patched in order to pick up the Redis class. That issue is still in progress -- I can see how it's forcing it to look in CRM/Utils/Cache but I'm not sure how to make it check an extension. At any rate, I've put the Redis.php into core and got it working with Pantheon Redis settings.

I'm tempted to just create a patch for this instead of using it as an extension. There are a few patches against CiviCRM that are required to have it working on Pantheon anyway.

**Comment by ChrisChinchilla** [comment]
I'm going to have to leave this in your hands for now. it's been a while since I last looked at the issue and I haven't done much CiviCRM work in the past 6 months. I don't think it's that complex, just needs a decision from core team.

Sorry!
